import Footer from '@/compenents/Footer/Footer'
import './globals.css'
import { Poppins } from 'next/font/google'
import Navbar from '@/compenents/Navbar/Navbar'

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500', '600','700', '800','900'] })

export const metadata = {
  title: 'PURU\'s',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  )
}
